site_name: An's Notes
homepage: https://shareli.me
site_description: A collection of notes and thoughts on various topics.
site_author: Truong An
site_url: https://shareli.me
repo_url: https://github.com/lovetruongan/My-Notes
repo_name: My Notes
copyright: Copyright &copy; 2024 Truong An
theme: 
  name: material
  logo: /assets/logo.png
  icon: 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features: 
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.scrollspy
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      toggle: 
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/brightness-5
        name: Switch to light mode
      primary: black
      accent: lime
  font:
    text: 'sans-serif'
    code: 'roboto-mono'
#Page tree
nav:
  - index.md
  - AWS:
    - AWS/AWS.md
  - Linux:
    - Linux/Linux.md
  - Docker:
    - Docker/Docker.md
  - Kubernetes:
    - Kubernetes/Kubernetes.md
  - Terraform:
    - Terraform/Terraform.md
  - CI/CD:
    - CICD/CI-CD.md
  - Networking:
    - Networking/Networking.md
  - Monitoring:
    - Monitoring/Monitoring.md
  - Blog:
      - blog/index.md

#plugin

plugins:
  - search
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

#additional
extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/lovetruongan/
    - name: Facebook
      icon: fontawesome/brands/facebook
      link: https://www.facebook.com/lovetruongan/
    - name: linkedin
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nguyễn-bùi-trường-an
#Extensions