site_name: An's Notes
site_description: A collection of notes and thoughts on various topics.
site_author: Truong An
site_url: https://shareli.me
repo_url: https://github.com/lovetruongan/My-Notes
repo_name: My Notes
copyright: Copyright &copy; 2024 Truong An
theme: 
  name: material
  logo: /assets/logo.png
  favicon: /assets/favicon.png
  icon: 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.tooltips
    - content.code.annotate 
    - content.code.select
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.scrollspy
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      toggle: 
        icon: material/brightness-4
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/brightness-5
        name: Switch to light mode
      primary: black
      accent: lime
  font:
    text: 'Roboto'
    code: 'roboto-mono'
#Page tree
nav:
  - index.md
  - AWS:
    - AWS/AWS.md
    - IAM & AWS CLI : AWS/IAM.md
    - Amazon Elastic Compute Cloud (EC2) : AWS/EC2.md
  - FCJ_2024:
    - FCJ_2024/FCJ_2024.md
    - FCJ_2024/Pipeline/pipeline.md
  - Linux:
    - Linux/Linux.md
    - Linux CheatSheet: Linux/Linux-Cheatsheet.md
    - Linux Advanced Commands: Linux/Advanced-command.md
  - Docker:
    - Docker/Docker.md
  - Kubernetes:
    - Kubernetes/Kubernetes.md
  - Terraform:
    - Terraform/Terraform.md
  - CI/CD:
    - CICD/CI-CD.md
  - Networking:
    - Networking/Networking.md
  - Monitoring:
    - Monitoring/Monitoring.md
  - Algorithm:
    - Algorithm/Algorithm.md
    - Algorithm/Test/test.md
  - Blog:
    - blog/index.md

#plugin

plugins:
  - search
  - blog:
      blog_toc: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags 
#additional
extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/lovetruongan/
    - name: Facebook
      icon: fontawesome/brands/facebook
      link: https://www.facebook.com/lovetruongan/
    - name: linkedin
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nguyễn-bùi-trường-an
#Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
